void TakeScreenshot();
void ToggleFog();
//void ToggleDither();
void CycleScaleFilter();
void CycleMipFilter();
void CycleFogMode();
//void CycleFillMode();
//void ToggleShading();
void ToggleAntialias();
void CycleAnisoLevel();
void ToggleZoom();
void IncreaseZoom();
void DecreaseZoom();
void RotateScreen();
void ToggleStatusText();
void ShowLastMessage();
void ToggleHardwareShader();
//void ToggleSoftwareShader();
//void ToggleSpecular();
void ToggleFpsCounter();
void IncreaseFog();
void DecreaseFog();
//void ToggleLightingFix();
void ToggleAAFix();
void IncreaseView();
void DecreaseView();
void IncreaseAI();
void DecreaseAI();
void IncreaseLOD();
void DecreaseLOD();
void ToggleCrosshair();
void NextTrack();
void DisableMusic();
void HaggleMore1();
void HaggleMore10();
void HaggleMore100();
void HaggleMore1000();
void HaggleMore10000();
void HaggleLess1();
void HaggleLess10();
void HaggleLess100();
void HaggleLess1000();
void HaggleLess10000();
void ToggleDistantLand();
void ToggleDistantStatics();
void ToggleGrass();
void ToggleMwMgeBlending();
void CycleWater();
void IncreaseFOV();
void DecreaseFOV();
void ToggleSkyReflection();
void MoveForward3PC ();
void MoveBack3PC ();
void MoveLeft3PC ();
void MoveRight3PC ();
void MoveDown3PC ();
void MoveUp3PC ();